node {

  ws("workspace/${env.JOB_NAME}/${env.BRANCH_NAME}") {
        stage('Checkout') {
          
            checkout scm
            sh ""
        }
        stage('Copy passwd file'){
          dir('ClientApp'){
            sh "chmod 755 src/environments/envset.sh"
            sh "sh src/environments/envset.sh"
          }
            sh "cp /var/jenkins_home/.npmrc /var/jenkins_home/workspace/'${env.JOB_NAME}'/${env.BRANCH_NAME}/ClientApp/"    
        }
        stage('NPM Install') {

            dir('ClientApp') {                
                sh 'npm install --verbose'
                        }
        }
      /*  stage('Test') {
            steps {
                sh 'npm run test'
            }
        }*/
        stage('Build') {
          
            dir('ClientApp'){
       
            //  sh "sed -i -e 's/testVariables123/${env.testVariables}/g' src/environments/environment.prod.ts"
              sh "set"
              sh 'ng build --configuration=production'
              sh "cp /var/jenkins_home/web.config /var/jenkins_home/workspace/'${env.JOB_NAME}'/${env.BRANCH_NAME}/ClientApp/dist/EMS/"
            }
        }
        stage('Upload to S3 bucket') {
      
            sh  "pwd"
            sh "aws s3 rm s3://emsbilling.org --recursive"
            sh "aws s3 cp ClientApp/dist/EMS/ s3://emsbilling.org --recursive --include '*' "
      }
  }
}
