node {

  ws("workspace/${env.JOB_NAME}/${env.BRANCH_NAME}") {
        stage('Checkout') {
          
            checkout scm
            sh ""
        }
        stage('Copy passwd file'){
         
            sh "cp /var/jenkins_home/.npmrc /var/jenkins_home/workspace/'${env.JOB_NAME}'/${env.BRANCH_NAME}/ClientApp/"
        }
        stage('NPM Install') {
            sh "echo $production"
            sh "echo 'Hello' "
            dir('ClientApp') {
                sh 'npm install --verbose'
            }
        }
      /*  stage('Test') {
            steps {
                sh 'npm run test'
            }
        }*/
        stage('Build') {
          
            dir('ClientApp'){
                sh 'ng build --configuration=production'
                sh "cp /var/jenkins_home/web.config /var/jenkins_home/workspace/'${env.JOB_NAME}'/${env.BRANCH_NAME}/ClientApp/dist/EMS/"
            }
        }
        stage('Upload to S3 bucket') {
            sh "echo $testVariables"
            sh  "pwd"
            sh "aws s3 rm s3://emsbillingwebsite --recursive"
            sh "aws s3 cp ClientApp/dist/EMS/ s3://emsbillingwebsite --recursive --include '*' "
      }
  }
}



