import { faArrowLeft, faAngleDown } from '@fortawesome/pro-light-svg-icons';
import {
  faPhonePlus,
  faPhone,
  faUserGroup,
  faBell,
  faShoppingCart,
  faShieldCheck,
  faChartTreeMap,
  faFiles,
  faLayerGroup,
  faPhoneAlt,
  faGrid2,
  faUserShield,
  faObjectsColumn,
  faTruck as faFlipTruck,
  faUsers,
  faArrowsRotate,
  faTrashCan,
  faCheck,
  faArrowRightFromBracket,
  faCircleQuestion,
  faSearch, 
  faHome
} from '@fortawesome/pro-solid-svg-icons';

export const fa = {
  faBell,
  faLayerGroup,
  faUserShield,
  faFiles,
  faPhone,
  faFlipTruck,
  faPhonePlus,
  faAngleDown,
  faArrowLeft,
  faUsers,
  faObjectsColumn,
  faPhoneAlt,
  faGrid2,
  faCheck,
  faTrashCan,
  faArrowsRotate,
  faArrowRightFromBracket,
  faCircleQuestion,
  faSearch,
  faHome
};
